"""
config_file.py
==============
Save and load gauge configuration parameters to/from a human-readable
key=value text file (CONFIG_TOOL_SPECIFICATION.md §12).

File format::

    # Gauge V4 Configuration
    # Generated by gauge-config-tool v1.0
    # Date: 2025-01-01

    m1_sweep=696
    m2_sweep=696
    ms_sweep=4032
    filter_vbatt=32
    # … one key=value per line; lines starting with # are comments

Usage::

    from config_file import ConfigFile
    cf = ConfigFile()
    cf.load_from_file("my_config.txt")
    print(cf.params["m1_sweep"])          # "696"
    cf.params["m1_sweep"] = "800"
    cf.save_to_file("my_config.txt")
"""

from __future__ import annotations

import datetime
import os
from typing import Dict, Optional


TOOL_VERSION = "1.0"


class ConfigFile:
    """Read and write gauge configuration key=value files."""

    def __init__(self) -> None:
        self.params: Dict[str, str] = {}

    # ------------------------------------------------------------------
    # Load
    # ------------------------------------------------------------------

    def load_from_file(self, path: str) -> Dict[str, str]:
        """Load *path* into :attr:`params` and return it.

        Lines starting with ``#`` or empty lines are ignored.
        Each remaining line must be ``key=value``.

        Raises:
            FileNotFoundError: if *path* does not exist.
            ValueError: if a line cannot be parsed as ``key=value``.
        """
        self.params = {}
        with open(path, "r", encoding="utf-8") as fh:
            for lineno, raw in enumerate(fh, start=1):
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" not in line:
                    raise ValueError(
                        f"{path}:{lineno}: expected 'key=value', got: {line!r}"
                    )
                key, _, value = line.partition("=")
                self.params[key.strip()] = value.strip()
        return self.params

    # ------------------------------------------------------------------
    # Save
    # ------------------------------------------------------------------

    def save_to_file(self, path: str, params: Optional[Dict[str, str]] = None) -> None:
        """Write *params* (or :attr:`params`) to *path*.

        Creates or overwrites the file.  Writes a header comment block
        with the tool version and generation date.

        Args:
            path:   Destination file path.
            params: If provided, used instead of :attr:`params`.
        """
        data = params if params is not None else self.params
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(f"# Gauge V4 Configuration\n")
            fh.write(f"# Generated by gauge-config-tool v{TOOL_VERSION}\n")
            fh.write(f"# Date: {now}\n")
            fh.write("\n")
            for key, value in sorted(data.items()):
                fh.write(f"{key}={value}\n")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def default_filename() -> str:
        """Return a timestamped default filename for new saves."""
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"gauge_config_{ts}.txt"
